name: Build test Sneaker-GCI Docker Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  Build-Test-Sneaker-GCI-Docker-image:
    name: Build Sneaker-GCI binaries and Docker image.
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Get current date
          id: date
          run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

        - name: Build image only
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false

        - name: Save the artifacts for this Docker build
          uses: actions/upload-artifact@v3
          with:
            name: builds
            path: build/

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
